image: debian

.build-script: &build-script
  - export PATH="$PWD:$PATH"
  - apt update
  # Install build dependencies
  - apt install --quiet --assume-yes bash curl git
  - curl -L 'https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz' > 'htmlq.tar.gz'
  - tar -xf 'htmlq.tar.gz'
  - chmod +x htmlq
  - curl -L 'https://github.com/getzola/zola/releases/download/v0.16.1/zola-v0.16.1-x86_64-unknown-linux-gnu.tar.gz' > 'zola.tar.gz'
  - tar -xf 'zola.tar.gz'
  - chmod +x zola
  # Pull in gdrive images
  - bash fetch-assets.bash
  # Echo out Git Version (for build-id)
  - echo -n " (" > templates/gitrev.html
  - git rev-parse --short head | head -c7 >> templates/gitrev.html
  - echo -n ")" >> templates/gitrev.html
  # Build Zola markup
  - zola build

build:
  script:
  - *build-script
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - *build-script
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
