# This Docker image (via DockerHub) provides for the curl command which we use to download files.
image: curlimages/curl

pages:
  stage: deploy
  script:
  - date -R
  - curl -L 'https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz' > 'htmlq-x86_64-linux.tar.gz'
  - tar -xf 'htmlq-x86_64-linux.tar.gz'
  - chmod +x htmlq
  - export PATH="$PWD:$PATH"
  - date -R
  - bash gdrive-img.bash
  - date -R
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
