image: rust

pages:
  stage: deploy
  script:
  - cargo install htmlq
  - bash gdrive-img.bash
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
