image: debian

pages:
  stage: deploy
  script:
  - apt update
  - apt install bash curl
  - curl -L 'https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz' > 'htmlq-x86_64-linux.tar.gz'
  - tar -xf 'htmlq-x86_64-linux.tar.gz'
  - chmod +x htmlq
  - export PATH="$PWD:$PATH"
  - bash gdrive-img.bash
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
