# We do some more advanced command line stuff, so use a minimal linux
image: alpine

pages:
  stage: deploy
  script:
  # Log the time
  - date -R
  # Enable networking
  - echo "ipv6" >> /etc/modules
  # Update package list
  - apk update
  # Install packages
  - apk add curl
  - apk add bash
  - apk add htmlq
  # Log the time
  - date -R
  # Pull images from drive
  - bash gdrive-img.bash
  # Log time
  - date -R
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
