# We do some more advanced command line stuff, so use a minimal linux
image: alpine

pages:
  stage: deploy
  script:
  # Log the time
  - date -R
  # Enable ipv6
  - echo "ipv6" >> /etc/modules
  # Update package list
  - apk update
  # Install packages
  # gcompat needed for htmlq (compiled with gcc)
  - apk add bash curl gcompat
  # Log the time
  - date -R
  # Install htmlq (for scraping gdrive)
  - curl -L 'https://github.com/mgdm/htmlq/releases/download/v0.4.0/htmlq-x86_64-linux.tar.gz' > 'htmlq-x86_64-linux.tar.gz'
  - tar -xf 'htmlq-x86_64-linux.tar.gz'
  - chmod +x htmlq
  - export PATH="$PWD:$PATH"
  - date -R
  # Pull images from drive
  - bash gdrive-img.bash
  # Log time
  - date -R
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
